# Generated by Django 5.2.17 on 2026-09-05 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mensagem', models.TextField(blank=True)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], default='whatsapp', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='tenants.garagem')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='vehicles.veiculo')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
