# Generated by Django 5.2.17 on 2026-09-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='lida',
        ),
        migrations.AddField(
            model_name='proposta',
            name='status',
            field=models.CharField(choices=[('nova', 'Nova'), ('em_contato', 'Em contato'), ('convertida', 'Vendido para esse cliente'), ('perdida', 'Sem retorno / Perdida')], default='nova', max_length=12),
        ),
    ]
