# Generated by Django 5.2.17 on 2026-09-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_proposta_lida_proposta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail (opcional)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='mensagem',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
    ]
