# Generated by Django 5.2.17 on 2026-09-24 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_proposta_email_alter_proposta_mensagem'),
        ('tenants', '0008_garagem_plano'),
        ('vehicles', '0006_alter_fotoveiculo_imagem_alter_fotoveiculo_ordem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail (opcional)')),
                ('tipo', models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro')], default='carro', max_length=5)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem (km)')),
                ('observacoes', models.TextField(blank=True, help_text='Estado de conservação, opcionais, motivo da venda — o que ajudar na avaliação.', verbose_name='Observações')),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('em_contato', 'Em contato'), ('avaliada', 'Avaliada'), ('comprada', 'Comprada'), ('recusada', 'Recusada')], default='nova', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='tenants.garagem')),
                ('veiculo_interesse', models.ForeignKey(blank=True, help_text='Veículo do catálogo que a pessoa quer levar na troca, quando o pedido veio da página dele.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='vehicles.veiculo')),
            ],
            options={
                'verbose_name': 'Avaliação de veículo',
                'verbose_name_plural': 'Avaliações de veículo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='avaliacoes/%Y/%m/')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='leads.avaliacao')),
            ],
            options={
                'verbose_name': 'Foto da avaliação',
                'verbose_name_plural': 'Fotos da avaliação',
            },
        ),
    ]
