# Generated by Django 5.2.17 on 2026-09-05 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoWebhookMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=60)),
                ('recurso_id', models.CharField(max_length=64)),
                ('payload_bruto', models.JSONField()),
                ('processado_com_sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento de webhook (Mercado Pago)',
                'verbose_name_plural': 'Eventos de webhook (Mercado Pago)',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_preapproval_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='pending', max_length=12)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proxima_cobranca_prevista', models.DateField(blank=True, null=True)),
                ('ultimo_pagamento_em', models.DateTimeField(blank=True, null=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('garagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='tenants.garagem')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
