# Generated by Django 5.2.17 on 2026-09-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseGaragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('nome_garagem', models.CharField(max_length=120, verbose_name='Nome da garagem')),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('atendido', models.BooleanField(default=False, verbose_name='Já atendido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interesse de garagem',
                'verbose_name_plural': 'Interesses de garagens',
                'ordering': ['-criado_em'],
            },
        ),
    ]
