# Generated by Django 5.2.17 on 2026-09-05 01:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('telefone_whatsapp', models.CharField(help_text='Somente dígitos, com DDI e DDD. Ex: 5517999999999', max_length=20)),
                ('email_contato', models.EmailField(max_length=254)),
                ('cidade', models.CharField(default='Catanduva', max_length=100)),
                ('taxa_juros_mensal_padrao', models.DecimalField(decimal_places=2, default=Decimal('2.5'), help_text='Taxa mensal (%) usada no simulador de financiamento.', max_digits=5)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('suspenso', 'Suspenso')], default='ativo', max_length=10)),
                ('suspensa_manualmente_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_aviso_atraso_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='garagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garagem',
                'verbose_name_plural': 'Garagens',
                'ordering': ['nome'],
            },
        ),
    ]
