# Generated by Django 5.2.17 on 2026-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='garagem',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='garagem',
            name='horario_funcionamento',
            field=models.CharField(blank=True, help_text='Ex: Seg a Sex, 8h às 18h', max_length=150),
        ),
        migrations.AddField(
            model_name='garagem',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
    ]
