# Generated by Django 5.2.17 on 2026-09-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_garagem_endereco_garagem_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='cor_destaque',
            field=models.CharField(default='#0F5C4D', help_text='Cor de destaque da sua vitrine, em hexadecimal (ex: #0F5C4D).', max_length=7),
        ),
    ]
