# Generated by Django 5.2.17 on 2026-09-21 21:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_garagem_cor_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagem',
            name='taxa_juros_mensal_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Em branco, o simulador usa a taxa média de mercado do Banco Central.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='Taxa de juros própria (% ao mês)'),
        ),
    ]
