# Generated by Django 5.2.17 on 2026-09-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_taxa_padrao_antiga_vira_em_branco'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='capa',
            field=models.ImageField(blank=True, help_text='Imagem larga que aparece atrás do cabeçalho da sua vitrine. Opcional.', null=True, upload_to='garagens/capas/', verbose_name='Faixa superior (capa)'),
        ),
        migrations.AddField(
            model_name='garagem',
            name='logo',
            field=models.ImageField(blank=True, help_text='Aparece ao lado do nome da garagem, na vitrine e no painel.', null=True, upload_to='garagens/logos/', verbose_name='Logo'),
        ),
    ]
