# Generated by Django 5.2.17 on 2026-09-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_garagem_capa_garagem_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='cor_titulo',
            field=models.CharField(default='#1A1A18', help_text='Cor do nome da garagem, da cidade e do botão "Fale conosco" no topo da vitrine — os três mudam juntos, para não sumir um deles se o fundo mudar de cor. Padrão: escuro.', max_length=7, verbose_name='Cor do nome da garagem'),
        ),
        migrations.AddField(
            model_name='garagem',
            name='fonte_titulo',
            field=models.CharField(choices=[('Big Shoulders', 'Moderna (padrão)'), ('Oswald', 'Condensada'), ('Bebas Neue', 'Impacto'), ('Anton', 'Extra bold'), ('Playfair Display', 'Clássica'), ('Archivo Black', 'Robusta'), ('Poppins', 'Geométrica'), ('Teko', 'Alta e fina'), ('Barlow Condensed', 'Condensada e limpa'), ('Rajdhani', 'Tecnológica')], default='Big Shoulders', help_text='Fonte do nome da garagem no topo da vitrine.', max_length=30, verbose_name='Fonte do nome da garagem'),
        ),
    ]
