# Generated by Django 5.2.17 on 2026-09-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_garagem_cor_titulo_garagem_fonte_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='plano',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', help_text='Define quantos veículos a garagem pode cadastrar (ver LIMITE_VEICULOS_POR_PLANO).', max_length=20),
        ),
    ]
