# Generated by Django 5.2.17 on 2026-09-24 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_garagem_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='ocultar_identidade_capa',
            field=models.BooleanField(default=False, help_text='Use se a sua faixa superior já tem sua marca desenhada nela. Só tem efeito quando existe pelo menos uma faixa cadastrada — sem faixa, o nome sempre aparece.', verbose_name='Mostrar só a faixa superior, sem logo/nome por cima'),
        ),
        migrations.AlterField(
            model_name='garagem',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='garagens/capas/', verbose_name='Faixa superior (capa) — descontinuado'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='garagens/capas/', verbose_name='Imagem')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='tenants.garagem')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
