# Generated by Django 5.2.17 on 2026-09-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_copia_capa_para_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garagem',
            name='capa',
        ),
    ]
