# Generated by Django 5.2.17 on 2026-09-24 23:31, ajustada à mão: adiciona os campos novos,
# copia o valor do campo antigo pros dois novos (quem tinha a identidade oculta continua com
# logo e nome ocultos, agora cada um com seu próprio interruptor) e só então remove o antigo —
# sem isso, o RemoveField apagaria essa informação antes de ter pra onde copiar.

from django.db import migrations, models


def copia_ocultar_identidade(apps, schema_editor):
    Garagem = apps.get_model('tenants', 'Garagem')
    Garagem.objects.filter(ocultar_identidade_capa=True).update(
        ocultar_logo_capa=True, ocultar_nome_capa=True,
    )


def reverte_para_ocultar_identidade(apps, schema_editor):
    Garagem = apps.get_model('tenants', 'Garagem')
    Garagem.objects.filter(ocultar_logo_capa=True, ocultar_nome_capa=True).update(
        ocultar_identidade_capa=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_remove_capa_antiga'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente ao escolher o endereço pela busca do Google Maps.', max_length=255, verbose_name='ID do lugar no Google Maps'),
        ),
        migrations.AddField(
            model_name='garagem',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Preenchida automaticamente ao escolher o endereço pela busca do Google Maps.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='garagem',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Preenchida automaticamente ao escolher o endereço pela busca do Google Maps.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='garagem',
            name='ocultar_logo_capa',
            field=models.BooleanField(default=False, help_text='Esconde a logo sobreposta ao cabeçalho, mesmo com uma cadastrada.', verbose_name='Ocultar a logo no topo da vitrine'),
        ),
        migrations.AddField(
            model_name='garagem',
            name='ocultar_nome_capa',
            field=models.BooleanField(default=False, help_text='Esconde o nome da garagem sobreposto ao cabeçalho — útil se a sua faixa já tem a marca desenhada nela. Sem logo nem nome ali, aparece um ícone de início no lugar.', verbose_name='Ocultar o nome no topo da vitrine'),
        ),
        migrations.RunPython(copia_ocultar_identidade, reverte_para_ocultar_identidade),
        migrations.RemoveField(
            model_name='garagem',
            name='ocultar_identidade_capa',
        ),
    ]
