# Generated by Django 5.2.17 on 2026-09-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_renomeia_ocultar_identidade_e_adiciona_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagem',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Deixado por uma versão anterior do seletor de endereço (baseado no Google Maps); quando presente, deixa o link "Como chegar" da vitrine mais preciso.', max_length=255, verbose_name='ID do lugar no Google Maps'),
        ),
        migrations.AlterField(
            model_name='garagem',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Preenchida automaticamente ao definir o endereço no mapa (painel da garagem).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='garagem',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Preenchida automaticamente ao definir o endereço no mapa (painel da garagem).', max_digits=10, null=True),
        ),
    ]
