# Generated by Django 5.2.17 on 2026-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_atualiza_textos_de_ajuda_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagem',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Sem uso atualmente — sobra de uma versão anterior do painel, que tinha um seletor com mapa.', max_length=255, verbose_name='ID do lugar no Google Maps'),
        ),
        migrations.AlterField(
            model_name='garagem',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Sem uso atualmente — sobra de uma versão anterior do painel, que tinha um seletor com mapa.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='garagem',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Sem uso atualmente — sobra de uma versão anterior do painel, que tinha um seletor com mapa.', max_digits=10, null=True),
        ),
    ]
