# Generated by Django 5.2.17 on 2026-10-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_garagem_google_place_id_alter_garagem_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='imagem_retrato',
            field=models.ImageField(blank=True, null=True, upload_to='garagens/capas/', verbose_name='Imagem (celular em pé)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(upload_to='garagens/capas/', verbose_name='Imagem (computador/celular na horizontal)'),
        ),
    ]
