# Generated by Django 5.2.17 on 2026-09-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(default='bcb-sgs-25471', max_length=40)),
                ('referencia', models.DateField(help_text='Mês a que a taxa se refere.')),
                ('taxa_mensal', models.DecimalField(decimal_places=2, help_text='Em % ao mês.', max_digits=5)),
                ('obtida_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taxa de referência',
                'verbose_name_plural': 'Taxas de referência',
                'ordering': ['-referencia'],
                'unique_together': {('fonte', 'referencia')},
            },
        ),
    ]
