# Generated by Django 5.2.17 on 2026-09-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaLoginFalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, db_index=True, max_length=150)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentativa de login falha',
                'verbose_name_plural': 'Tentativas de login falhas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
