# Generated by Django 5.2.17 on 2026-09-05 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('ano_fabricacao', models.PositiveSmallIntegerField()),
                ('ano_modelo', models.PositiveSmallIntegerField()),
                ('quilometragem', models.PositiveIntegerField()),
                ('combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico')], max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('destaque', models.BooleanField(default=False, help_text='Aparece na frontpage da garagem.')),
                ('disponivel', models.BooleanField(default=True, help_text='Desmarque para ocultar da vitrine (vendido/reservado).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='tenants.garagem')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-destaque', '-criado_em'],
                'unique_together': {('garagem', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FotoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='veiculos/%Y/%m/')),
                ('principal', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='vehicles.veiculo')),
            ],
            options={
                'verbose_name': 'Foto do veículo',
                'verbose_name_plural': 'Fotos do veículo',
                'ordering': ['-principal', 'ordem'],
            },
        ),
    ]
