# Generated by Django 5.2.17 on 2026-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='aceita_troca',
            field=models.BooleanField(default=False, help_text='Exibe o selo "Aceita troca" no anúncio.'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cilindrada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cilindradas (cc), quando aplicável. Ex: 160', null=True),
        ),
    ]
