# Generated by Django 5.2.17 on 2026-09-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_veiculo_aceita_troca_veiculo_cilindrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='potencia_motor',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Potência do motor em litros — apenas para carros. Ex: 1.0, 1.6, 2.0', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro')], default='moto', max_length=5),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cilindrada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cilindradas (cc) — apenas para motos. Ex: 160', null=True),
        ),
    ]
