# Generated by Django 5.2.17 on 2026-09-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_veiculo_potencia_motor_veiculo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título.', max_length=170),
        ),
    ]
