# Generated by Django 5.2.17 on 2026-09-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_veiculo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Álcool'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico')], max_length=10),
        ),
    ]
