# Generated by Django 5.2.17 on 2026-09-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_veiculo_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoveiculo',
            name='imagem',
            field=models.ImageField(upload_to='veiculos/%Y/%m/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='fotoveiculo',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='fotoveiculo',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='Foto principal'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.PositiveSmallIntegerField(verbose_name='Ano de fabricação'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.PositiveSmallIntegerField(verbose_name='Ano do modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cilindrada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cilindradas (cc) — apenas para motos. Ex: 160', null=True, verbose_name='Cilindrada (cc)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Álcool'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico')], max_length=10, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Aparece no carrossel de destaques da vitrine.'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar da vitrine (vendido/reservado).', verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='potencia_motor',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Potência do motor em litros — apenas para carros. Ex: 1.0, 1.6, 2.0', max_digits=2, null=True, verbose_name='Potência do motor (litros)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='quilometragem',
            field=models.PositiveIntegerField(verbose_name='Quilometragem (km)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
    ]
