# Generated by Django 5.2.17 on 2026-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_fotoveiculo_imagem_alter_fotoveiculo_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cambio',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('cvt', 'CVT'), ('automatizado', 'Automatizado')], max_length=12, verbose_name='Câmbio'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='portas',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2 portas'), (3, '3 portas'), (4, '4 portas'), (5, '5 portas')], help_text='Apenas para carros.', null=True, verbose_name='Portas'),
        ),
    ]
